language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - REQUIREMENTS="django>=1.8,<1.9"
  - REQUIREMENTS="django>=1.9,<1.10"
  - REQUIREMENTS="django>=1.10,<1.11"
  - REQUIREMENTS="django>=1.11,<2.0"
  - REQUIREMENTS="django>=2.0,<2.1"
  - REQUIREMENTS="https://github.com/django/django/archive/master.tar.gz"
matrix:
  exclude:
    - python: "2.7"
      env:  REQUIREMENTS="django>=2.0,<2.1"
    - python: "2.7"
      env: REQUIREMENTS="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.4"
      env: REQUIREMENTS="django>=2.0,<2.1"
    - python: "3.4"
      env: REQUIREMENTS="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.5"
      env: REQUIREMENTS="django>=1.8,<1.9"
    - python: "3.6"
      env: REQUIREMENTS="django>=1.8,<1.9"
    - python: "3.6"
      env: REQUIREMENTS="django>=1.9,<1.10"
    - python: "3.6"
      env: REQUIREMENTS="django>=1.10,<1.11"
    - python: "3.6"
      env: REQUIREMENTS="django>=1.11,<2.0"
  allow_failures:
    - env: REQUIREMENTS="https://github.com/django/django/archive/master.tar.gz"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install flake8 coveralls $REQUIREMENTS
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - DJANGO_SETTINGS_MODULE=tests.settings nosetests --with-coverage --cover-package=django_crontab
after_success:
  - coveralls
